config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  namespace :admin do
    root "dashboards#index"
    get "dashboards" => "dashboards#index", :as => :dashboards

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
    end

    devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :passwords => 'admin/users/passwords', :skip => [:registrations]

    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
      patch 'users' => 'devise/registrations#update', :as => 'update_user_registration'
    end

    resources :users
    resources :categories
    resources :courses
    resources :subjects
    resources :instructors
    resources :types
    resources :blogs
    resources :registrations
    resources :students, only: [:index, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  resources :home
  resources :abouts, only: [:index]
  resources :instructors, only: [:index, :show]
  resources :courses, only: [:index, :show] do
    resources :registrations, only: [:show, :create, :new]
  end
  
  resources :contacts
  resources :pages, only: [:index]
  resources :blogs, only: [:index, :show]

  get 'signup' => "audiences#new", :as => :signup
  get 'logout' => "sessions#destroy", :as => :logout
  get 'login' => "sessions#new", :as => :login

  resources :events do
    resources :audiences
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audience.rb
class Audience < ApplicationRecord
  before_save :update_slug

  def update_slug
    self.slug = title.parameterize
  end

  def to_param
    slug
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  #Callback
  before_save :update_slug

  #Association
  belongs_to :user
  belongs_to :type, required: true

  #Validation

  #Method

  def update_slug
    self.slug = title.parameterize
  end

  def to_param
    slug
  end

  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :title, presence: true
  validates :title, uniqueness: {case_sensitive: false}
end

app/models/category.rb
class Category < ApplicationRecord
  #CallBack
  before_save :update_slug

  #Association
  belongs_to :user
  has_many :courses
  #Validation
  validates :category_name, presence: true
  validates :category_name, uniqueness: {case_sensitive: false}

  #Method
  def update_slug
    self.slug = category_name.parameterize
  end

  def to_param
    slug
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  #Association

  #Validation
  validates :name, presence: true
  validates :email, presence: true
  #Method
end

app/models/contactinfo.rb
class Contactinfo < ApplicationRecord
  #Association
  belongs_to :user

  #Validation

  #Method
end

app/models/course.rb
class Course < ApplicationRecord

  #CallBack
  before_save :update_slug
  #Association
  belongs_to :user, optional: true
  belongs_to :instructor, optional: true
  belongs_to :category
  has_many :subjects, inverse_of: :course
  has_many :registrations

  accepts_nested_attributes_for :subjects, :reject_if => :all_blank, :allow_destroy => true
  #Validation
  validates :course_name, uniqueness: {case_sensitive: false}
  #Method

  def update_slug
    self.slug = course_name.parameterize
  end

  def to_param
    slug
  end

  #Contact Var
  SECTION_SELECT_SESSION = [
    "Morning",
    "Afternoon"
  ]

  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/event.rb
class Event < ApplicationRecord
  before_save :update_slug

  has_many :audiences
  validates :title, uniqueness: { case_sensitive: false }
  def update_slug
    self.slug = title.parameterize
  end

  def to_param
    slug
  end

end

app/models/instructor.rb
class Instructor < ApplicationRecord
  #callback
  before_save :update_slug
  #Association
  belongs_to :user
  has_many :courses
  #Validation
  validates :firstname, :lastname, presence: true
  validates :email, uniqueness: {case_sensitive: false}
  #Method
  def update_slug
    self.slug = email.parameterize
  end

  def to_param
    slug
  end

  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/registration.rb
class Registration < ApplicationRecord
  before_save :update_slug
  #Association
  belongs_to :user, optional: true
  belongs_to :course

  #Validation
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true
  validates :email, uniqueness: {case_sensitive: false}
  validates :phone, presence: true, :numericality => true
  #Method
  def update_slug
    self.slug = email.parameterize
  end

  def to_param
    slug
  end
end

app/models/section.rb
class Section < ApplicationRecord
  #Association
  belongs_to :user

  #Validation
  
  #Method
end

app/models/subject.rb
class Subject < ApplicationRecord
  #CallBack

  #Association
  belongs_to :course

  #Validation
  validates :subject_name, presence: true
  #Method

end

app/models/type.rb
class Type < ApplicationRecord
  #Callback
  before_save :update_slug

  #Association
  belongs_to :user
  has_many :blogs

  #Validation
  validates :type_name, presence: true
  validates :type_name, uniqueness: {case_sensitive: false}
  #Method
  def update_slug
    self.slug = type_name.parameterize
  end

  def to_param
    slug
  end
end

app/models/user.rb
class User < ApplicationRecord
  #CallBack
  before_save :update_slug

  #Association
  has_many :blogs
  has_many :categories
  has_many :instructors
  has_many :courses
  has_many :sections
  has_many :contactinfos
  has_many :registrations
  has_many :types
  has_many :blogs

  #Validation
  validates :username, presence: true
  validates :username , uniqueness: {case_sensitive: false}

  #Method

  def set_default_role
    self.role ||= :user
  end

  def update_slug
    self.slug = username.parameterize
  end

  def to_param
    slug
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  has_many :ahoy_events, class_name: "Ahoy::Event"
  belongs_to :home, optional: true
  belongs_to :blog, optional: true
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_flash_message
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error' if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe

  end

  def get_active(id, correct: "active", incorrect: "inactive")
    if id === 1
      correct
    else
      incorrect
    end
  end

  def fullname(first, last)
    "#{first} #{last}"
  end

  def status_converter(status, correct: 'Paid', incorrect: 'Unpaid')
    if status
     correct
    else
      incorrect
    end
  end

  def check_if_course_equal_20(search, correct: '', incorrect: '')
    if search == 3 || search >= 3
      incorrect
    else
      correct
    end
  end

  def time_ago(time)
    "#{time_ago_in_words(time)} ago"
  end

  def section_time(section)
    if section == "Morning"
      "8am to 11am"
    elsif section == "Afternoon"
      "2pm to 5pm"
    end
  end

  def title(blog_title)
    content_for(:title) {blog_title}
  end

  def meta_description(blog_text)
    content_for(:meta_description) {blog_text}
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/css/_a1.html.erb
<style media="screen">
/*
*  Owl Carousel - Animate Plugin
*/
.owl-carousel .animated {
-webkit-animation-duration: 1000ms;
animation-duration: 1000ms;
-webkit-animation-fill-mode: both;
animation-fill-mode: both;
}
.owl-carousel .owl-animated-in {
z-index: 0;
}
.owl-carousel .owl-animated-out {
z-index: 1;
}
.owl-carousel .fadeOut {
-webkit-animation-name: fadeOut;
animation-name: fadeOut;
}

@-webkit-keyframes fadeOut {
0% {
  opacity: 1;
}

100% {
  opacity: 0;
}
}
@keyframes fadeOut {
0% {
  opacity: 1;
}

100% {
  opacity: 0;
}
}

/*
* 	Owl Carousel - Auto Height Plugin
*/
.owl-height {
-webkit-transition: height 500ms ease-in-out;
-moz-transition: height 500ms ease-in-out;
-ms-transition: height 500ms ease-in-out;
-o-transition: height 500ms ease-in-out;
transition: height 500ms ease-in-out;
}

/*
*  Core Owl Carousel CSS File
*/
.owl-carousel {
display: none;
width: 100%;
-webkit-tap-highlight-color: transparent;
/* position relative and z-index fix webkit rendering fonts issue */
position: relative;
z-index: 1;
}
.owl-carousel .owl-stage {
position: relative;
-ms-touch-action: pan-Y;
}
.owl-carousel .owl-stage:after {
content: ".";
display: block;
clear: both;
visibility: hidden;
line-height: 0;
height: 0;
}
.owl-carousel .owl-stage-outer {
position: relative;
overflow: hidden;
/* fix for flashing background */
-webkit-transform: translate3d(0px, 0px, 0px);
}
.owl-carousel .owl-controls .owl-nav .owl-prev,
.owl-carousel .owl-controls .owl-nav .owl-next,
.owl-carousel .owl-controls .owl-dot {
cursor: pointer;
cursor: hand;
-webkit-user-select: none;
-khtml-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
}
.owl-carousel.owl-loaded {
display: block;
}
.owl-carousel.owl-loading {
opacity: 0;
display: block;
}
.owl-carousel.owl-hidden {
opacity: 0;
}
.owl-carousel .owl-refresh .owl-item {
display: none;
}
.owl-carousel .owl-item {
position: relative;
min-height: 1px;
float: left;
-webkit-backface-visibility: hidden;
-webkit-tap-highlight-color: transparent;
-webkit-touch-callout: none;
-webkit-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
}
.owl-carousel .owl-item img {
display: block;
width: 100%;
-webkit-transform-style: preserve-3d;
}
.owl-carousel.owl-text-select-on .owl-item {
-webkit-user-select: auto;
-moz-user-select: auto;
-ms-user-select: auto;
user-select: auto;
}
.owl-carousel .owl-grab {
cursor: move;
cursor: -webkit-grab;
cursor: -o-grab;
cursor: -ms-grab;
cursor: grab;
}
.owl-carousel.owl-rtl {
direction: rtl;
}
.owl-carousel.owl-rtl .owl-item {
float: right;
}

/* No Js */
.no-js .owl-carousel {
display: block;
}

/*
* 	Owl Carousel - Lazy Load Plugin
*/
.owl-carousel .owl-item .owl-lazy {
opacity: 0;
-webkit-transition: opacity 400ms ease;
-moz-transition: opacity 400ms ease;
-ms-transition: opacity 400ms ease;
-o-transition: opacity 400ms ease;
transition: opacity 400ms ease;
}
.owl-carousel .owl-item img {
transform-style: preserve-3d;
}

/*
* 	Owl Carousel - Video Plugin
*/
.owl-carousel .owl-video-wrapper {
position: relative;
height: 100%;
background: #000;
}
.owl-carousel .owl-video-play-icon {
position: absolute;
height: 80px;
width: 80px;
left: 50%;
top: 50%;
margin-left: -40px;
margin-top: -40px;
background: url("owl.video.play.png") no-repeat;
cursor: pointer;
z-index: 1;
-webkit-backface-visibility: hidden;
-webkit-transition: scale 100ms ease;
-moz-transition: scale 100ms ease;
-ms-transition: scale 100ms ease;
-o-transition: scale 100ms ease;
transition: scale 100ms ease;
}
.owl-carousel .owl-video-play-icon:hover {
-webkit-transition: scale(1.3, 1.3);
-moz-transition: scale(1.3, 1.3);
-ms-transition: scale(1.3, 1.3);
-o-transition: scale(1.3, 1.3);
transition: scale(1.3, 1.3);
}
.owl-carousel .owl-video-playing .owl-video-tn,
.owl-carousel .owl-video-playing .owl-video-play-icon {
display: none;
}
.owl-carousel .owl-video-tn {
opacity: 0;
height: 100%;
background-position: center center;
background-repeat: no-repeat;
-webkit-background-size: contain;
-moz-background-size: contain;
-o-background-size: contain;
background-size: contain;
-webkit-transition: opacity 400ms ease;
-moz-transition: opacity 400ms ease;
-ms-transition: opacity 400ms ease;
-o-transition: opacity 400ms ease;
transition: opacity 400ms ease;
}
.owl-carousel .owl-video-frame {
position: relative;
z-index: 1;
}

</style>

app/views/css/_a10.html.erb
<style media="screen">
  .slick-slider{position:relative;display:block;box-sizing:border-box;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;-webkit-touch-callout:none;-khtml-user-select:none;-ms-touch-action:pan-y;touch-action:pan-y;-webkit-tap-highlight-color:transparent}.slick-list{position:relative;display:block;overflow:hidden;margin:0;padding:0}.slick-list:focus{outline:none}.slick-list.dragging{cursor:pointer;cursor:hand}.slick-slider .slick-track,.slick-slider .slick-list{-webkit-transform:translate3d(0, 0, 0);-moz-transform:translate3d(0, 0, 0);-ms-transform:translate3d(0, 0, 0);-o-transform:translate3d(0, 0, 0);transform:translate3d(0, 0, 0)}.slick-track{position:relative;top:0;left:0;display:block}.slick-track:before,.slick-track:after{display:table;content:''}.slick-track:after{clear:both}.slick-loading .slick-track{visibility:hidden}.slick-slide{display:none;float:left;height:100%;min-height:1px}[dir='rtl'] .slick-slide{float:right}.slick-slide img{display:block}.slick-slide.slick-loading img{display:none}.slick-slide.dragging img{pointer-events:none}.slick-initialized .slick-slide{display:block}.slick-loading .slick-slide{visibility:hidden}.slick-vertical .slick-slide{display:block;height:auto;border:1px solid transparent}.slick-arrow.slick-hidden{display:none}
</style>

app/views/css/_a3.html.erb
<style media="screen">
a.meanmenu-reveal{display:none}
.mean-container .mean-bar {
background: transparent none repeat scroll 0 0;
float: left;
min-height: 42px;
padding: 0;
position: relative;
width: 100%;
z-index: 9;
}
.mean-container a.meanmenu-reveal{width:22px;height:22px;padding:13px 13px 11px;top:0;right:0;cursor:pointer;color:#fff;text-decoration:none;font-size:16px;text-indent:-9999em;line-height:22px;font-size:1px;display:block;font-family:Arial,Helvetica,sans-serif;font-weight:700;float: right;}
.mean-container a.meanmenu-reveal span{display:block;background:#fff;height:3px;margin-top:3px}
.mean-container .mean-nav{float:left;width:100%;background:#0c1923}
.mean-container .mean-nav ul{padding:0;margin:0;width:100%;list-style-type:none}
.mean-container .mean-nav ul li {
background: #f8f8f8 none repeat scroll 0 0;
float: left;
position: relative;
width: 100%;
border-top: 1px solid #ddd;
}
.mean-container .mean-nav ul li:first-child {border: 0}
.mean-container .mean-nav ul li a {
background: #f8f8f8 none repeat scroll 0 0;
color: #666666;
display: block;
float: left;
font-size: 12px;
margin: 0;
padding: 1em 5%;
text-align: left;
text-decoration: none;
text-transform: uppercase;
width: 90%;
font-weight: bold;
}
.mobile-menu-area {
background: #262626;
}
.mean-container .mean-nav ul li li a {
border-top: 1px solid rgba(255, 255, 255, 0.25);
opacity: 0.75;
padding: 1em 10%;
text-shadow: none !important;
visibility: visible;
width: 80%;
font-weight: normal;
text-transform: capitalize;
color: #444;
}
.mean-container .mean-nav ul li.mean-last a{border-bottom:0;margin-bottom:0}
.mean-container .mean-nav ul li li li a{width:70%;padding:1em 15%}
.mean-container .mean-nav ul li li li li a{width:60%;padding:1em 20%}
.mean-container .mean-nav ul li li li li li a{width:50%;padding:1em 25%}
.mean-container .mean-nav ul li a:hover {
background: #f8f8f8 none repeat scroll 0 0;
color: #F47E1E;
}
.mean-container .mean-nav ul li a.mean-expand{
width:26px;
height: 15px;
  margin-top: 1px;
  padding: 12px !important;
text-align:center;
position:absolute;
right:0;top:0;
z-index:2;
font-weight:700;
background:rgba(255,255,255,.1);
border:0!important;
background: #F8F8F8;
}
.mean-container .mean-nav ul li a.mean-expand:hover {
background: #f8f8f8;
}
.mean-container .mean-push{float:left;width:100%;padding:0;margin:0;clear:both}
.mean-nav .wrapper{width:100%;padding:0;margin:0}
.mean-container .mean-bar,.mean-container .mean-bar *{-webkit-box-sizing:content-box;-moz-box-sizing:content-box;box-sizing:content-box}
.mean-remove{display:none!important}
.mean-container .mean-bar::after {
color: #ffffff;
content: "MENU";
font-size: 21px;
left: 5%;
position: absolute;
top: 12px;
}
</style>

app/views/shared/_css.html.erb
<%=render "css/a"%>
<%=render "css/a1"%>
<%=render "css/a2"%>
<%=render "css/a3"%>
<%=render "css/a4"%>
<%=render "css/a5"%>
<%=render "css/a6"%>
<%=render "css/a7"%>
<%=render "css/a8"%>
<%=render "css/a9"%>
<%=render "css/a10"%>
<%=render "css/a11"%>
<%=render "css/a12"%>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container-fluid clearfix">
    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2018 <a href="http://www.codehubacademy.com/" target="_blank">Codehubacademy</a>. All rights reserved.</span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Powered By Codehubacademy <i class="mdi mdi-heart text-danger"></i></span>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar horizontal-layout col-lg-12 col-12 p-0">
  <div class="container d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-top">
      <a class="navbar-brand brand-logo" href="/admin"><img src="/codehublogo.png" alt="logo"/></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center">
      <form class="search-field ml-auto" action="#">
        <div class="form-group mb-0">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="mdi mdi-magnify"></i></span>
            </div>
            <input type="text" class="form-control">
          </div>
        </div>
      </form>
      <ul class="navbar-nav navbar-nav-right mr-0">
        <li class="nav-item dropdown ml-4">
          <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
            <i class="mdi mdi-bell-outline"></i>
            <span class="count bg-warning">4</span>
          </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
            <a class="dropdown-item py-3">
              <p class="mb-0 font-weight-medium float-left">You have 4 new notifications
              </p>
              <span class="badge badge-pill badge-inverse-info float-right">View all</span>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-inverse-success">
                  <i class="mdi mdi-alert-circle-outline mx-0"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <h6 class="preview-subject font-weight-normal text-dark mb-1">Application Error</h6>
                <p class="font-weight-light small-text mb-0">
                  Just now
                </p>
              </div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-inverse-warning">
                  <i class="mdi mdi-comment-text-outline mx-0"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <h6 class="preview-subject font-weight-normal text-dark mb-1">Settings</h6>
                <p class="font-weight-light small-text mb-0">
                  Private message
                </p>
              </div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-inverse-info">
                  <i class="mdi mdi-email-outline mx-0"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <h6 class="preview-subject font-weight-normal text-dark mb-1">New user registration</h6>
                <p class="font-weight-light small-text mb-0">
                  2 days ago
                </p>
              </div>
            </a>
          </div>
        </li>
        <li class="nav-item dropdown d-none d-xl-inline-block">
          <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
            <%if current_admin_user.image%>
              <img class="img-xs rounded-circle" src="<%=current_admin_user.image%>" alt="Profile image">
            <%else%>
              <img class="img-xs rounded-circle" src="/user.png" alt="Profile">
            <%end%>


          </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
            <a class="dropdown-item p-0">
              <div class="d-flex border-bottom">
                <div class="py-3 px-4 d-flex align-items-center justify-content-center"><i class="mdi mdi-bookmark-plus-outline mr-0 text-gray"></i></div>
                <div class="py-3 px-4 d-flex align-items-center justify-content-center border-left border-right"><i class="mdi mdi-account-outline mr-0 text-gray"></i></div>
                <div class="py-3 px-4 d-flex align-items-center justify-content-center"><i class="mdi mdi-alarm-check mr-0 text-gray"></i></div>
              </div>
            </a>
            <%=link_to "Manage Accounts", edit_admin_user_path(current_admin_user), class: "dropdown-item"%>
            <%=link_to "Logout", destroy_admin_user_session_path, method: :delete, class: "dropdown-item"%>
          </div>
        </li>
      </ul>
      <button class="navbar-toggler align-self-center" type="button" data-toggle="minimize">
        <span class="mdi mdi-menu"></span>
      </button>
    </div>
  </div>
  <div class="nav-bottom">
    <div class="container">
      <ul class="nav page-navigation">
        <li class="nav-item">
          <a href="/admin/" class="nav-link"><i class="link-icon mdi mdi-television"></i><span class="menu-title">DASHBOARD</span></a>
        </li>
        <li class="nav-item">
          <%=link_to admin_users_path, class: "nav-link" do%>
            <i class="link-icon mdi mdi-television"></i><span class="menu-title">Administrator</span>
          <%end%>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link"><i class="link-icon mdi mdi-asterisk"></i><span class="menu-title">Regist Management</span><i class="menu-arrow"></i></a>
          <div class="submenu">
            <ul class="submenu-item">
              <li class="nav-item">
                <%=link_to "Registration Report", admin_registrations_path, class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%=link_to "Student Report", admin_students_path, class: "nav-link"%>
              </li>
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link"><i class="link-icon mdi mdi-asterisk"></i><span class="menu-title">Course Management</span><i class="menu-arrow"></i></a>
          <div class="submenu">
            <ul class="submenu-item">
              <li class="nav-item">
                <%=link_to "Instructor", admin_instructors_path, class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%=link_to "Category", admin_categories_path, class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%=link_to "Subject", admin_subjects_path, class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%=link_to "Course", admin_courses_path, class: "nav-link"%>
              </li>
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link"><i class="link-icon mdi mdi-asterisk"></i><span class="menu-title">Content Management</span><i class="menu-arrow"></i></a>
          <div class="submenu">
            <ul class="submenu-item">
              <li class="nav-item">
                <a class="nav-link" href="#">Slideshow</a>
              </li>
              <li class="nav-item">
                <%=link_to "Types", admin_types_path, class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%=link_to "News", admin_blogs_path, class: "nav-link"%>
              </li>
              <li class="nav-item"><a class="nav-link" href="#">Skills & Experences</a></li>
              <li class="nav-item"><a class="nav-link" href="#">Gallery</a></li>
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>