config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  namespace :admin do
    root "dashboards#index"
    get "dashboards" => "dashboards#index", :as => :dashboards

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
    end

    devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :passwords => 'admin/users/passwords', :skip => [:registrations]

    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
      patch 'users' => 'devise/registrations#update', :as => 'update_user_registration'
    end

    resources :users
    resources :categories
    resources :courses
    resources :subjects
    resources :instructors
    resources :types
    resources :blogs
    resources :registrations
    resources :students, only: [:index, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  resources :home
  resources :abouts, only: [:index]
  resources :instructors, only: [:index, :show]
  resources :courses, only: [:index, :show] do
    resources :registrations, only: [:show, :create, :new]
  end
  
  resources :contacts
  resources :pages, only: [:index]
  resources :blogs, only: [:index, :show]

  get 'signup' => "audiences#new", :as => :signup
  get 'logout' => "sessions#destroy", :as => :logout
  get 'login' => "sessions#new", :as => :login

  resources :events do
    resources :audiences
  end
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  #callback
  before_save :update_slug
  #Association
  belongs_to :user
  has_many :courses
  #Validation
  validates :firstname, :lastname, presence: true
  validates :email, uniqueness: {case_sensitive: false}
  #Method
  def update_slug
    self.slug = email.parameterize
  end

  def to_param
    slug
  end

  has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/admin/instructors_controller.rb
class Admin::InstructorsController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :admin_only?

  def index
    @instructor = current_admin_user.instructors.build
    @instructors = Instructor.all
  end

  def show
    @instructor = Instructor.find_by_slug(params[:id])
  end

  def new

  end

  def create
    instructor_params[:profession].split(',').map do |n|
      Instructor.new(profession: n).save
    end
    @instructor = current_admin_user.instructors.build(instructor_params)
    if @instructor.save
      respond_to do |format|
        flash.now[:notice] = "Successful Created"
        format.html { redirect_to admin_instructors_path }
        format.js
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please fill the field blank or instructor Duplicated"
        format.html { redirect_to admin_instructors_path }
        format.js { render template: "admin/instructors/instructor_error.js.erb" }
      end
    end
  end

  def edit
    @instructor = Instructor.find_by_slug(params[:id])
  end

  def update
    @instructor = Instructor.find_by_slug(params[:id])
    if @instructor.update(instructor_params)
      redirect_to admin_instructor_path(@instructor), notice: "Successful Updated"
    else
      render :edit
    end
  end

  def destroy
    @instructor = Instructor.destroy(params[:id])
    respond_to do |format|
      flash.now[:error] = "Delete"
      format.html { redirect_to admin_instructors_url }
      format.js
    end
  end

  private
    def admin_only?
      unless  current_admin_user.admin?
        unless @user == current_admin_user
          redirect_to admin_dashboard_path, notice: "Access Denied"
        end
      end
    end

    def instructor_params
      params.required(:instructor).permit(:firstname, :lastname, :dob, :email, :phone, :description, :title, :course_id, :profession, :status, :image)
    end
end

app/controllers/instructors_controller.rb
class InstructorsController < FrontEndApplicationController
  def index
    @search = Course.ransack(params[:search])
    @courses = @search.result
    @instructors = Instructor.all
  end

  def show
    @instructor = Instructor.find_by_slug(params[:id])
  end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/admin/instructors/_instructor.html.erb
<tr class="delete_instructor_<%=instructor.id%>">
  <td>
    <%=instructor.id%>
  </td>

  <td>
    <%= "#{instructor.firstname} #{instructor.lastname}"%>
  </td>

  <td>
    <%=instructor.dob%>
  </td>

  <td>
    <%=instructor.email%>
  </td>

  <td>
    <%=instructor.phone%>
  </td>

  <td>
    <%=instructor.title%>
  </td>

  <td>
    <%=status_converter(instructor.status, correct: "Activated", incorrect: "inactive")%>
  </td>

  <td>
    <%=time_ago(instructor.created_at)%>
  </td>


  <td>
    <%=form_for([:admin, instructor], remote: true) do |f|%>
      <%=link_to admin_instructor_path(instructor), title: "View" do %>
        View
      <%end%>
      <%=link_to edit_admin_instructor_path(instructor), title: "Edit",id: "show-form_#{instructor.id}" do %>
        Edit
      <%end%>
    <%end%>
  </td>
</tr>

app/views/admin/instructors/_instructor_form.html.erb
<div class="row">
  <div class="col-md-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Course</h4>
        <div class="instructor-form">
          <%=simple_form_for([:admin, instructor], remote: true)do |f|%>
            <div class="form-group">
              <label for="exampleInputEmail3">First Name</label>
              <%=f.text_field :firstname, class: "form-control", placeholder: "Course Name", required: true%>
            </div>

            <div class="form-group">
              <label for="exampleInputEmail3">Last Name</label>
              <%=f.text_field :lastname, class: "form-control", placeholder: "Course Name", required: true%>
            </div>

            <div class="form-group">
              <label for="exampleInputEmail3">Date Of Birth</label>
              <%=f.text_field :dob, class: "form-control", placeholder: "Course Name", required: true%>
            </div>

            <div class="form-group">
              <label for="exampleInputEmail3">Email</label>
              <%=f.text_field :email, class: "form-control", placeholder: "Course Name", required: true%>
            </div>

            <div class="form-group">
              <label for="exampleInputEmail3">Phone</label>
              <%=f.text_field :phone, class: "form-control", placeholder: "Course Name", required: true%>
            </div>

            <div class="form-group">
              <label for="exampleInputEmail3">Title</label>
              <%=f.text_field :title, class: "form-control", placeholder: "Course Name", required: true%>
            </div>

            <div class="form-group">
              <label for="exampleInputEmail3">Profession</label>
              <%=f.text_area :profession, class: "form-control", placeholder: "Subject Name", id: "subject_name"%>
            </div>

            <div class="form-group">
              <%=f.input :description, class: "form-control", as: :ckeditor, input_html: {ckeditor: {toolbar: 'Full'} }%>
            </div>

            <div class="form-group">
              <div class="control-group file-upload" id="file-upload1">
                <h3>Upload Photo</h3>
                <div class="image-box text-center"><p>Upload Image</p><img src="" alt=""></div>
                <div class="controls">
                    <%=f.file_field :image%>
                </div>
              </div>
            </div>

            <div class="modal-footer">
              <%=f.submit "Save", class: "btn brn-success mr-2"%>
              <button class="btn btn-light" data-dismiss="modal" aria-label="Close">Cancel</button>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/admin/instructors/create.js.erb
$("input#instructor_fistname").val("");
$("input#instructor_lastname").val("");
$("input#instructor_dob").val("");
$("input#instructor_email").val("");
$("input#instructor_phone").val("");
$("input#instructor_title").val("");
$("#instructor-errors").html(" ");
$("#instructor-success").html("<%= custom_flash_message%>");
$("#instructor-index").append("<%=escape_javascript render(@instructor)%>");

$(function() {
  $('.delete_instructor_<%=@instructor.id%>').submitOnCheck();
});

$('.delete_instructor_<%=@instructor.id%>').submitOnCheck();

app/views/admin/instructors/destroy.js.erb
$('.delete_instructor_<%=@instructor.id%>').remove();

app/views/admin/instructors/edit.html.erb
<%=render "shared/header"%>
<div class="container-fluid page-body-wrapper">
  <div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Personal Information</h4>
              <div class="instructor-form">
                <%=simple_form_for([:admin, @instructor])do |f|%>
                    <div class="form-group">
                      <label for="exampleInputEmail3">First Name</label>
                      <%=f.text_field :firstname, class: "form-control", placeholder: "instructor Name", required: true%>
                    </div>

                    <div class="form-group">
                      <label for="exampleInputEmail3">Last Name</label>
                      <%=f.text_field :lastname, class: "form-control", placeholder: "instructor Name", required: true%>
                    </div>

                    <div class="form-group">
                      <label for="exampleInputEmail3">Date Of Birth</label>
                      <%=f.text_field :dob, class: "form-control", placeholder: "instructor Name", required: true%>
                    </div>

                    <div class="form-group">
                      <label for="exampleInputEmail3">Email</label>
                      <%=f.text_field :email, class: "form-control", placeholder: "Course Name", required: true%>
                    </div>

                    <div class="form-group">
                      <label for="exampleInputEmail3">Phone</label>
                      <%=f.text_field :phone, class: "form-control", placeholder: "Course Name", required: true%>
                    </div>

                    <div class="form-group">
                      <label for="exampleInputEmail3">Title</label>
                      <%=f.text_field :title, class: "form-control", placeholder: "instructor Name", required: true%>
                    </div>

                    <div class="form-group">
                      <label for="exampleInputEmail3">Profession</label>
                      <%=f.text_area :profession, class: "form-control", placeholder: "Subject Name", id: "subject_name"%>
                    </div>

                    <div class="form-group">
                      <%=f.input :description, class: "form-control", as: :ckeditor, input_html: {ckeditor: {toolbar: 'Full'} }%>
                    </div>

                    <div class="form-group">
                      <div class="control-group file-upload" id="file-upload1">
                        <h3>Upload Photo</h3>
                        <div class="image-box text-center"><p>Upload Image</p><img src="" alt=""></div>
                        <div class="controls">
                            <%=f.file_field :image%>
                        </div>
                      </div>
                    </div>

                    <div class="form-group d-flex justify-content-between">
                      <div class="form-check form-check-flat mt-0">
                        <label class="form-check-label">
                          <%=f.check_box :status, class: "form-check-input"%>
                          If instructor still working status will be active if not update information
                        </label>
                      </div>
                    </div>

                    <div class="modal-footer">
                      <%=f.submit "Save", class: "btn brn-success mr-2"%>
                      <%=link_to "Cancel", admin_instructors_path,class: "btn btn-light"%>
                    </div>
                  </div>
                <%end%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
    <!-- content-wrapper ends -->
    <!-- partial:partials/_footer.html -->
    <%=render "shared/footer"%>
    <!-- partial -->
  </div>
  <!-- main-panel ends -->
</div>

app/views/admin/instructors/index.html.erb
<%=render "shared/header"%>
<div class="container-fluid page-body-wrapper">
  <div class="main-panel">
    <div class="content-wrapper">
      <button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#exampleModal">Add instructor
        <i class="mdi mdi-play-circle ml-1"></i>
      </button>
      <div class="col-12 grid-margin">
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add instructor</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                      <div id="instructors">
                        <div id="instructor-errors"></div>
                        <div id="instructor-success"></div>
                        <%=render partial: "instructor_form", locals: {instructor: @instructor}%>
                      </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Modal Ends -->
        </div>


      <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-12 table-responsive">
                <table id="order-listing" class="table">
                  <thead>
                    <tr>
                        <th>ID</th>
                        <th>Fullname</th>
                        <th>Dob</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Title</th>
                        <th>Status</th>
                        <th>Created At</th>
                        <th style="text-align: center;">Actions</th>
                    </tr>
                  </thead>
                  <tbody id="instructor-index">
                    <%if @instructors.any?%>
                    <%= render @instructors%>
                  <%end%>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
    </div>
    <!-- content-wrapper ends -->
    <!-- partial:partials/_footer.html -->
    <%=render "shared/footer"%>
    <!-- partial -->
  </div>
  <!-- main-panel ends -->
</div>

app/views/admin/instructors/instructor_error.js.erb
$("input#instructor_fistname").val("");
$("input#instructor_lastname").val("");
$("input#instructor_dob").val("");
$("input#instructor_email").val("");
$("input#instructor_phone").val("");
$("input#instructor_title").val("");
$("#instructor-errors").html("<br><%= j render partial: 'layouts/flash_errors', locals: {flash: :flash}%>");

app/views/admin/instructors/instructor_success.js.erb
$("input#instructor_fistname").val("");
$("input#instructor_lastname").val("");
$("input#instructor_dob").val("");
$("input#instructor_email").val("");
$("input#instructor_phone").val("");
$("input#instructor_title").val("");
$("#instructor-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");

app/views/admin/instructors/show.html.erb
<%=render "shared/header"%>
<div class="container-fluid page-body-wrapper">
  <div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
        <div class="col-md-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Category Information</h5>
              <ul class="bullet-line-list">
                <li>
                  <p class="mb-2">Full Name</p>
                  <h6><%="#{@instructor.firstname} #{@instructor.lastname}"%></h6>
                </li>

                <li>
                  <p class="mb-2">Date Of Birth/p>
                  <h6><%=@instructor.dob%></h6>
                </li>

                <li>
                  <p class="mb-2">Email</p>
                  <h6><%=@instructor.phone%></h6>
                </li>

                <li>
                  <p class="mb-2">Title</p>
                  <h6><%=status_converter(@instructor.status)%></h6>
                </li>

                <li>
                  <p class="mb-2">Full Name</p>
                  <h6><%="#{@instructor.firstname} #{@instructor.lastname}"%></h6>
                </li>

              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    <!-- content-wrapper ends -->
    <!-- partial:partials/_footer.html -->
    <%=render "shared/footer"%>
    <!-- partial -->
  </div>
  <!-- main-panel ends -->
</div>